CREATE TABLE blogs (
	id SERIAL UNIQUE,
	ref VARCHAR(20) UNIQUE NOT NULL,
	date_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO blogs (ref) VALUES ('default');

ALTER TABLE comments ADD COLUMN blog VARCHAR(20) DEFAULT 'default' REFERENCES blogs(ref) ON DELETE CASCADE;
